services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_challenge
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./data:/apiapp/data
    working_dir: /apiapp

volumes:
  data: